### PR TITLE
Enable overlap_comm for better performance

### PR DESCRIPTION
**Pull request by li-plus**
Overlap gradient allreduce and backward. Port my PR to ds-chat https://github.com/microsoft/DeepSpeedExamples/pull/846 here.

### CODE REVIEW

**Review by wuxibin89 — APPROVED** [review]

**Comment by hijkzzz** [comment]
This option should be turned on depending on the situation because overlap comm takes up a lot of extra GPU memory

**Comment by wuxibin89** [comment]
> This option should be turned on depending on the situation because overlap comm takes up a lot of extra GPU memory

Well, may be we should expose some deepspeed configuration and let user passing them by command line arguments?

**Comment by hijkzzz** [comment]
I have reverted this MR, since it causes the training unstable: https://wandb.ai/janhu9527/openrlhf_train_ppo?workspace=user-janhu9527

**Comment by hijkzzz** [comment]
ee202110e00ce2391e1509c2cc7afe7

**Pull request merged**
